version: '3.9'

services:

  envoy:
    image: envoyproxy/envoy:v1.22.0
    ports:
      - "8080:8080"
      - "9901:9901"
    volumes:
      - "./envoy.yaml:/etc/envoy/envoy.yaml"

  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--http_port 8222"